import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'http://127.0.0.1:54321';
// Use the new service role key that was generated by the latest CLI start
const supabaseServiceKey = 'sb_secret_N7UND0UgjKTVK-Uodkm0Hg_xSvEMPvz'; 
const supabase = createClient(supabaseUrl, supabaseServiceKey);

async function fix() {
  console.log("Fixing Auth Users...");
  
  // 1. Wipe the profiles table to drop the foreign key locks
  const { error: delProfErr } = await supabase.from('profiles').delete().neq('id', '00000000-0000-0000-0000-000000000000');
  if (delProfErr) console.error("Error deleting profiles:", delProfErr.message);

  // 2. Fetch and delete existing auth users
  const { data: listData } = await supabase.auth.admin.listUsers();
  if (listData?.users) {
    for (const u of listData.users) {
      await supabase.auth.admin.deleteUser(u.id);
      console.log(`Deleted old auth user: ${u.email}`);
    }
  }

  // 3. Recreate users via GoTrue Admin API (This ensures the password hashes correctly!)
  const usersToCreate = [
    { email: 'admin@pms.com', role: 'admin', name: 'System Admin' },
    { email: 'owner@demo.com', role: 'owner', name: 'Demo Owner', prop: '11111111-1111-1111-1111-111111111111' },
    { email: 'staff@demo.com', role: 'staff', name: 'Demo Staff', prop: '11111111-1111-1111-1111-111111111111' },
  ];

  for (const def of usersToCreate) {
    const { data: userResp, error: userErr } = await supabase.auth.admin.createUser({
      email: def.email,
      password: 'password123',
      email_confirm: true,
      user_metadata: { role: def.role }
    });

    if (userErr) {
      console.error(`Failed to create ${def.email}:`, userErr.message);
      continue;
    }

    const newId = userResp.user.id;
    console.log(`Created ${def.email} with new ID: ${newId}`);

    // 4. Re-link the profiles
    const { error: profErr } = await supabase.from('profiles').insert({
      id: newId,
      email: def.email,
      full_name: def.name,
      role: def.role,
      property_id: def.prop || null
    });

    if (profErr) {
      console.error(`Failed to create profile for ${def.email}:`, profErr.message);
    }
  }
  
  // 5. Test Login
  console.log("\nTesting Login...");
  const { error: loginErr } = await supabase.auth.signInWithPassword({
    email: 'admin@pms.com',
    password: 'password123'
  });
  
  if (loginErr) {
    console.log("Login Test Failed:", loginErr.message);
  } else {
    console.log("Login Test SUCCESS! Password hashing is fixed.");
  }
}

fix();
