apiVersion: v1
kind: Secret
metadata:
  name: pms-prod-secrets
  namespace: default # Or your specific namespace, usually 'default'
type: Opaque
data:
  NEXT_PUBLIC_SUPABASE_URL: aHR0cHM6Ly9uamJsZW10cmtxdG5pandybnZqcC5zdXBhYmFzZS5jbw==
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW5ocWMzVjNhbWwyWlhSc2JYcDZZbTVuWlhWNUlpd2ljbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUzTnpVNU9UVXpNakFzSW1WNGNDSTZNakE1TVRVM01UTXlNSDAuazJ4QTdiN0YzZXl2Y2pyR3RYM2V6Sjl3V2dEYnFYYXhEMnhlblZrb1VjSQ==
  SUPABASE_SERVICE_ROLE_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW5ocWMzVjNhbWwyWlhSc2JYcDZZbTVuWlhWNUlpd2ljbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUzTnpVNU9UVXpNakFzSW1WNGNDSTZJbk5sY25acFkyVmZjbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUzTnpVNU9UVXpNakFzSW1WNGNDSTZNVGMzTlRrNU5UTXlNQ3dpWlhod0lqb3lNRGt4TlRjeE16SXdmUS54U1ptSmRuenZ2VGpwQ0l3anVSSFZfQUJCWVZnd0dLZTBjV3V0Z1B1cFNn
  RESEND_API_KEY: cmVfVDZYYnRhbjhfTkNydkh3SEtyQjVXdWUzdnFoeVlTR1Zo