apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pms-ingress
  namespace: pms-namespace
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # Add these three lines to fix the health check
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: '3000' 
spec:
  ingressClassName: alb
  rules:
  - host: sub.staysync.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pms-service
            port:
              number: 80
