apiVersion: v1
kind: Service
metadata:
  name: pms-service
  namespace: default
  labels:
    app: pms-frontend
spec:
  selector:
    app: pms-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
