apiVersion: v1
kind: Service
metadata:
  name: pms-frontend
  namespace: default
spec:
  selector:
    app: pms-frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
