global:
  scrape_interval: 5s # How often to pull data

scrape_configs:
  - job_name: 'pms-nextjs-app'
    static_configs:
      # 'host.docker.internal' allows the Docker container to access localhost:3000 on your Mac/Linux machine
      - targets: ['host.docker.internal:3000'] 
